# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sa6kGkp9MH6fdx4x4DVjoiNAMp1jPCOu
"""

import pandas as pd
import numpy as np

df=pd.read_csv('student_scores.csv')

df.head()

df.shape

df.describe()

import seaborn as sns
import matplotlib.pyplot as plt

sns.jointplot(x='hours',y='scores',data=df, kind='scatter')

df.corr()

plt.figure()

sns.heatmap(df.corr(),annot=True)

data=df[['scores']]
target=df['hours']

data.shape

target.shape

data.head()

target.head()

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.7,random_state=0)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression
regessor=LinearRegression()
regessor.fit(x_train,y_train)

print('y intercept:',regessor.intercept_)

print('slope:',regessor.coef_)

y_train_pred=regessor.predict(x_train)

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,y_train_pred,color='blue')
plt.title('Hours vs Scores')
plt.xlabel('Hours')
plt.ylabel('Scores')
plt.show()

residual=y_train-y_train_pred

print(residual)

sns.displot(residual, kind='kde')

plt.scatter(y_train,residual)
plt.show()

y_test_pred=regessor.predict(x_test)

temp_df= pd.DataFrame({'Actual':y_test,'Predicted':y_test_pred})

temp_df

from sklearn import metrics

print('Mean Absolute Error:',metrics.mean_absolute_error(y_test,y_test_pred))
print('Mean Squared Error:',metrics.mean_squared_error(y_test,y_test_pred))
print('Root Mean Squared Error:',np.sqrt(metrics.mean_squared_error(y_test,y_test_pred)))

metrics.median_absolute_error(y_test,y_test_pred)

print(metrics.r2_score(y_test,y_test_pred))

r2=metrics.r2_score(y_test,y_test_pred)
n=len(y_test)
k=x_test.shape[1]
r2_adj=1-((1-r2)*(n-1)/(n-k-1))
print(r2_adj)

import statsmodels.api as sm

x_train_sm=sm.add_constant(x_train)
lr= sm.OLS(y_train,x_train_sm).fit()

lr.params

print(lr.summary())

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,y_train_pred,color='blue')
plt.title('Hours vs Scores')
plt.xlabel('Hours')
plt.ylabel('Scores')