# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12R7zbIbR9P0Z7zGDM97lrLAPBsinumaq
"""

import pandas as pd
import numpy as np

df=pd.read_csv('student_scores.csv')

df.shape

df.head()

data=df[['scores']]
target=df['hours']

data

target

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(data,target, train_size=0.7, random_state=0)

print(X_train.shape, Y_train.shape)

print(X_test.shape, Y_test.shape)

print(X_train)

print(Y_train)

print(X_test)

print(Y_test)

from sklearn.linear_model import LinearRegression

regressor=LinearRegression()

regressor.fit(X_train,Y_train)

print('y intercept:',regressor.intercept_)
print('slope:',regressor.coef_)

Y_test_pred=regressor.predict(X_test)

temp_df=pd.DataFrame({'Actual':Y_test,'Predicted':Y_test_pred})

import seaborn as sns

sns.histplot(Y_test,color='red',bins=5,alpha=0.5)
sns.histplot(Y_test_pred,color='blue',bins=5,alpha=0.5)

from sklearn import metrics

print('Root Mean squared error:',np.sqrt(metrics.mean_squared_error(Y_test,Y_test_pred)))

print(metrics.r2_score(Y_test,Y_test_pred))